export const data = [
  {
    _id: 1,
    title: "Apple",
    info: "Delivery with in 24 hours",
    logo: "apple.png",
    bkColor: "rgba(92, 0, 230, 0.2)",
    to: "#",
  },
  {
    _id: 2,
    title: "Asus",
    info: "Delivery with in 24 hours",
    logo: "asus.png",
    bkColor: "rgba(0, 158, 55, 0.2)",
    to: "#",
  },
  {
    _id: 3,
    title: "Canon",
    info: "Delivery with in 24 hours",
    logo: "canon.png",
    bkColor: "rgba(230, 0, 92, 0.2)",
    to: "#",
  },
  {
    _id: 4,
    title: "Microsoft",
    info: "Delivery with in 24 hours",
    logo: "microsoft.png",
    bkColor: "rgba(0, 165, 230, 0.2)",
    to: "#",
  },
  {
    _id: 5,
    title: "Huawei",
    info: "Delivery with in 24 hours",
    logo: "huawei.png",
    bkColor: "rgba(230, 0, 0, 0.2)",
    to: "#",
  },
  {
    _id: 6,
    title: "Samsung",
    info: "Delivery with in 24 hours",
    logo: "samsung.png",
    bkColor: "rgba(19, 0, 230, 0.2)",
    to: "#",
  },
  {
    _id: 7,
    title: "hp",
    info: "Delivery with in 24 hours",
    logo: "hp.png",
    bkColor: "rgba(230, 123, 0, 0.2)",
    to: "#",
  },
  {
    _id: 8,
    title: "dell",
    info: "Delivery with in 24 hours",
    logo: "dell.png",
    bkColor: "rgba(207, 0, 230, 0.2)",
    to: "#",
  },
];
