export const data = [
  {
    _id: 1,
    info: "Explore our furniture & home furnishing range.",
    bkImage: "sofa.jpg",
    bkColor: "#f6f2d3",
    textColor: "#ca981a",
    discount: 100,
    to: "#",
  },
  {
    _id: 2,
    info: "Enjoy discount all types of books & gadgets item.",
    bkImage: "book.jpg",
    bkColor: "#f9dbdb",
    textColor: "#921f23",
    discount: 29,
    to: "#",
  },
  {
    _id: 3,
    info: "Explore our all types dresses for men.",
    bkImage: "clothes.jpg",
    bkColor: "#f3e4da",
    textColor: "#93643e",
    discount: 67,
    to: "#",
  },
  {
    _id: 4,
    info: "Enjoy discount all types of educational accessories.",
    bkImage: "bag.jpg",
    bkColor: "#d2f7ec",
    textColor: "#083629",
    discount: 59,
    to: "#",
  },
];
