export const data = [
  {
    _id: 1,
    title: "A good walk requires the right shoes.",
    productsCount: 10,
    image: "shoes2.png",
    to: "#",
  },
  {
    _id: 2,
    title: "36,000 models of the best modern fashions.",
    productsCount: 10,
    image: "clothes2.png",
    to: "#",
  },
  {
    _id: 3,
    title: "Special offers and discounts on mobile phones.",
    productsCount: 10,
    image: "phone.png",
    to: "#",
  },
  {
    _id: 4,
    title: "The best sports bags for travel and outings.",
    productsCount: 10,
    image: "bag.png",
    to: "#",
  },
  {
    _id: 5,
    title: "Fresh vegetable will fulfill your life's needs.",
    productsCount: 10,
    image: "superMarket.png",
    to: "#",
  },
  {
    _id: 6,
    title: "Office supplies and stationery with special discounts.",
    productsCount: 10,
    image: "Stationery2.png",
    to: "#",
  },
  {
    _id: 7,
    title: "The original New York Times bestseller.",
    productsCount: 10,
    image: "book.png",
    to: "#",
  },
  {
    _id: 8,
    title: "Special sale of men's and women's perfumes.",
    productsCount: 10,
    image: "perfume.png",
    to: "#",
  },
];
